FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./

RUN pip install uv

RUN uv sync --frozen --no-dev

COPY . .

RUN mkdir -p /app/data/uploads /app/data/output

EXPOSE 8000

CMD ["uv", "run", "uvicorn","app.main:app","--host", "0.0.0.0", "--port", "8000"]